### ISSUE TITLE
Size Map

### ISSUE THREAD

**Issue by Shainara** [antihax/antihax.github.io#1]
Hello. 
When I place tags with resources (json/islands), he thinks that the map is 15x15.

Config:
const config = {
    ServersX: 5,
    ServersY: 5,
    Cluster: 2,
    Version: 60,
}

"worldX": 6575807.5,
 "worldY": 4803430.0,
https://cdn.discordapp.com/attachments/371582219048845323/630880750849491011/unknown.png

Help please configure. It turns out a beautiful map.

**Comment by antihax** [comment]
This was silently resolved a while back to help private server owners.
