### ISSUE TITLE
Question: Slippy Maps

### ISSUE THREAD

**Issue by mozuki345** [antihax/antihax.github.io#2]
Hello,

first I find the idea and implementation Great. thank you very much for it!

I'm just thinking how do I get slippy maps of grid and names?

Everything else I have managed but how to make the other two I do not know unfortunately and I can not find anything. 

best regards

**Comment by antihax** [comment]
This requires the ServerGridEditor from Grapeshot Games. The best way to find the latest version is the #downloads channel on the Atlas Server Owner Support discord: https://discord.gg/Kpkg8uR
